#:schema node_modules/wrangler/config-schema.json
name = "complicated-forms"
compatibility_date = "2024-10-22"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".svelte-kit/cloudflare"
