name: deploy to cloudflare prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: deploy to cloudflare
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        
      - name: install dependencies
        run: bun i

      - name: configure environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: build for prod
        run: bun run build
        env:
          PERMIT_IO_SHARING: false

      - name: deploy to cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
