name: deploy to cloudflare prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy to cloudflare
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        
      - name: install dependencies
        run: bun i

      - name: build for prod
        run: bun run build

      - name: deploy to cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            DB_TYPE
            POSTGRES_HOST
            POSTGRES_PORT
            POSTGRES_DB
            POSTGRES_USER
            POSTGRES_PASS
        env:
          DB_TYPE: ${{ vars.DB_TYPE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.PORTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.PORTGRES_DB }}
          POSTGRES_USER: ${{ secrets.PORTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.PORTGRES_PASS }}
          
      
